apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qso4ym467-java-springboot 
  janus-idp.io/tekton: qso4ym467-java-springboot
  backstage.io/kubernetes-id: qso4ym467-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qso4ym467-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml